version: '3.8'

services: 
  redis:
    image: redis
    volumes:
      - redis-data:/data
    networks:
      - basic_stat_api_net
    ports:
      - 6379
  app:
    build: .
    container_name: basic_stat_api
    depends_on: 
      - redis
    command: bundle exec shotgun --host=0.0.0.0 --port=3000 config.ru
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - basic_stat_api_net
    volumes:
      - .:/code
      - bundle-cache:/usr/local/bundle

  chrome:
    # Currently, Apple M1 is only supported in unnumbered "latest" versions.
    # See https://github.com/browserless/chrome/issues/1393
    image: browserless/chrome:latest
    ports:
      - '3333:3333'
    environment:
      PORT: 3333
      # Set connection timeout for debugging
      # https://docs.browserless.io/docs/docker.html#connection-timeout
      CONNECTION_TIMEOUT: 600000
    networks:
      - basic_stat_api_net

volumes:
  redis-data:
  bundle-cache:

networks:
  basic_stat_api_net:
    driver: bridge
    name: basic_stat_api_net
